### ISSUE TITLE
unknown or URL pattern 警告

### ISSUE THREAD

**Issue by DennisThink** [hzeyuan/x-cards#1]
打开插件管理器有一个警告。

Permission 'https://x-cards.net/*' is unknown or URL pattern is malformed.

![image](https://github.com/user-attachments/assets/439f39c6-291b-44a5-b46e-d9155866f86f)

操作系统Win10 64Bit。
浏览器版本
Nearly up to date! Relaunch Chrome to finish updating.
Version 127.0.6533.74 (Official Build) (64-bit)

**Comment by kaixindelele** [comment]
win11也有类似的报错~

**Comment by hzeyuan** [comment]
已修复
