### ISSUE TITLE
是否可以点击卡片，复制md到剪贴板

### ISSUE THREAD

**Issue by xyh2132** [hzeyuan/x-cards#4]
导出到本地，再打开，是个麻烦的过程，能否实现复制markdown到粘贴板

**Comment by hzeyuan** [comment]
下个版本支持

**Comment by hzeyuan** [comment]
Already supported

**Comment by xyh2132** [comment]
希望继续优化下： 目前复制到markdown格式，带有网址的链接会自动被加上省略号导致无法打开链接，同时把喜欢数，点赞数都复制到了，清理这些无用的吧
