### ISSUE TITLE
x-card read browser history

### ISSUE THREAD

**Issue by DennisThink** [hzeyuan/x-cards#5]
![image](https://github.com/user-attachments/assets/3d81e2d0-6c1b-4846-a6ba-63f8c930f98b)

why x-card need to read my browser history?

**Comment by hzeyuan** [comment]
Hello, I checked your screenshot, and I can tell you clearly that our
plug-in does not collect your browsing history, so I don’t know why this
picture is displayed.
Our code is open source. You can view it at
https://github.com/hzeyuan/x-cards. It is unreserved and can be guaranteed
to be the same version as the one released.
If you have any other doubts, or you are a developer, you have correctly
judged whether we have obtained your data and engaged in some inappropriate
behavior.

Of course, if you still don’t believe it, you can tell me and I will try my
best to prove it to you, I promise.

Finally, thank you for supporting my plug-in. I am an independent
developer, thank you.

DennisThink ***@***.***> 于2024年8月22日周四 13:50写道：

**Comment by DennisThink** [comment]
I don't know why, it did not appear anymore. Maybe it is a bug of Chrome.

**Comment by hzeyuan** [comment]
https://www.producthunt.com/new/products/x-cards

Hey man, excuse me for disturbing you. I am about to do my first ranking in
my life on producthunt. Can you give me a vote then? Thank you.

DennisThink ***@***.***> 于2024年8月22日周四 14:47写道：
